---
abstract: 'Detect freq of tones in an audio file or stream'
author:
  - 'Mike Greb <michael@thegrebs.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.2, Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Audio-Analyzer-ToneDetect
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Audio::Analyzer: 0
  Sort::Key::Top: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/mikegrb/Audio-Analyzer-ToneDetect/issues
  homepage: https://github.com/mikegrb/Audio-Analyzer-ToneDetect
  repository: https://github.com/mikegrb/Audio-Analyzer-ToneDetect.git
version: 0.02
x_contributors:
  - 'mikegrb <mgreb@linode.com>'
